/* HERE YOU PUT THE ACTIONS CONSTANTS */

export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const USER_EDIT = "USER_EDIT";

export const INTEGRATION_ADD = "INTEGRATION_ADD";
export const SELECT_INTEGRATION = "SELECT_INTEGRATION";
export const SELECT_STORE = "SELECT_STORE";
export const ERROR_SELECTING_STORE = "ERROR_SELECTING_STORE";

export const ADD_CORRIDORS = "ADD_CORRIDORS";

export const ADD_MAPPED_ITEM = "ADD_MAPPED_ITEM";

export const REMOVE_MAPPED_ITEM = "REMOVE_MAPPED_ITEM";

export const HOME_PAGE_LOADING = "HOME_PAGE_LOADING";
export const HOME_PAGE_ERROR = "HOME_PAGE_ERROR";

export const ADD_SIMULATED_ITEMS = "ADD_SIMULATED_ITEMS";
export const ADD_SIMULATED_ITEM = "ADD_SIMULATED_ITEM";
export const UPDATE_SIMULATED_ITEMS = "UPDATE_SIMULATED_ITEMS";
